load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
    name = "even_number",
    srcs = [
        "src/even_number.c",
        "src/even_number.h",
    ],
    visibility = ["//applications/app2:__subpackages__"],
)
