load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "unity",
    srcs = [
        "unity.c",
        "unity.h",
        "unity_internals.h",
        ],
    visibility = ["//applications/app2:__subpackages__"],
)
